### ISSUE TITLE
Error message with test run

### ISSUE THREAD

**Issue by rcdorsey** [eggls6/objectsInField#4]
When running the test config file in an 'oif-dev' conda environment created with spicepy 5.0.0 and python 3.10.2, I get the following error message:

<img width="710" alt="objectInField-errorMessage-testRun" src="https://user-images.githubusercontent.com/65519533/155949712-a4145469-2e9e-43fe-8174-a6b7486a021e.png">

**Comment by eggls6** [comment]
Resolved for now by downgrading spicepy to version 4.0.1. Will be fixed once unit tests show that omitting the other two arguments in the offending function does not change the results.
