### ISSUE TITLE
Spiceypy error in sso.py

### ISSUE THREAD

**Issue by samncorn** [eggls6/objectsInField#6]
Running the test dataset ('test/input.config') returns an error on line 329 with the spiceypy function mxvg, using version 5.0.1.

'''
TypeError: mxvg() takes 2 positional arguments but 4 were given
'''
Reverting to 4.0.1 serves as a temporary fix.

**Comment by samncorn** [comment]
Duplicate of #4

**Comment by eggls6** [comment]
same as issue #4
